# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_shouye', '0002_auto_20170817_0028'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsinfo',
            name='company_name',
            field=models.CharField(default=b'', max_length=20),
        ),
    ]
