# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_shouye', '0005_auto_20170826_1521'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrowImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('growimage', models.ImageField(upload_to=b'growimages')),
                ('beizhu', models.CharField(max_length=50)),
                ('growtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_shouye.GoodsInfo')),
            ],
        ),
    ]
