# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 14:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('df_shouye', '0006_growimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='rtype',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
    ]
