# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_shouye', '0007_auto_20170829_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fertilizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usetime', models.DateTimeField()),
                ('fertilizername', models.CharField(max_length=50)),
                ('leixing', models.CharField(max_length=50)),
                ('yongliang', models.CharField(max_length=50)),
                ('pingpai', models.CharField(max_length=50)),
                ('gongyingshang', models.CharField(max_length=50)),
                ('ftype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_shouye.GoodsInfo')),
            ],
        ),
    ]
