# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('df_shouye', '0008_fertilizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizer',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='growimage',
            name='isDelete',
            field=models.BooleanField(default=False),
        ),
    ]
