# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('df_shouye', '0012_pesticide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_temp', models.FileField(blank=True, upload_to=b'airtemp')),
                ('air_hum', models.FileField(blank=True, upload_to=b'airhum')),
                ('soil_temp', models.FileField(blank=True, upload_to=b'soiltemp')),
                ('soil_hum', models.FileField(blank=True, upload_to=b'soilhum')),
                ('pH_value', models.FileField(blank=True, upload_to=b'pHvalue')),
                ('envType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='df_shouye.GoodsInfo')),
            ],
        ),
    ]
